FROM rust:bookworm AS build-stage
WORKDIR /backend
COPY Cargo.toml Cargo.lock ./
COPY src ./src
COPY entity ./entity
RUN cargo fetch
RUN cargo build --release


FROM debian:bookworm-slim AS final-stage
RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*
ENV ROCKET_ADDRESS=0.0.0.0
ENV ROCKET_PORT=8000
COPY --from=build-stage /backend/target/release/backend /backend
COPY assets /assets
EXPOSE 8000
CMD ["/backend"]
