//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "climbing_grades")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub climbing_grade_id: i32,
    pub name: String,
    pub grade_context: String,
    pub numverical_value: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::training_templates::Entity")]
    TrainingTemplates,
}

impl Related<super::training_templates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TrainingTemplates.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
