//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "climbers")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub climber_id: i32,
    pub email: String,
    pub password_hash: String,
    pub username: String,
    pub firstname: String,
    pub lastname: String,
    pub profile_pic_id: i32,
    pub weight: i32,
    pub birth_date: Date,
    pub lead_rp_indoor: i32,
    pub lead_rp_outdoor: i32,
    pub boulder_rp_indoor: i32,
    pub boulder_rp_outdoor: i32,
    pub max_force_right: i32,
    pub max_force_left: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::climbing_grades::Entity",
        from = "Column::BoulderRpIndoor",
        to = "super::climbing_grades::Column::ClimbingGradeId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ClimbingGrades4,
    #[sea_orm(
        belongs_to = "super::climbing_grades::Entity",
        from = "Column::BoulderRpIndoor",
        to = "super::climbing_grades::Column::ClimbingGradeId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ClimbingGrades3,
    #[sea_orm(
        belongs_to = "super::climbing_grades::Entity",
        from = "Column::LeadRpIndoor",
        to = "super::climbing_grades::Column::ClimbingGradeId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ClimbingGrades2,
    #[sea_orm(
        belongs_to = "super::climbing_grades::Entity",
        from = "Column::LeadRpOutdoor",
        to = "super::climbing_grades::Column::ClimbingGradeId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ClimbingGrades1,
    #[sea_orm(has_many = "super::favourite_gyms::Entity")]
    FavouriteGyms,
    #[sea_orm(has_many = "super::favourite_trainings::Entity")]
    FavouriteTrainings,
    #[sea_orm(has_many = "super::gyms::Entity")]
    Gyms,
    #[sea_orm(
        belongs_to = "super::profile_pics::Entity",
        from = "Column::ProfilePicId",
        to = "super::profile_pics::Column::ProfilePicId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ProfilePics,
    #[sea_orm(has_many = "super::training_records::Entity")]
    TrainingRecords,
    #[sea_orm(has_many = "super::training_templates::Entity")]
    TrainingTemplates,
}

impl Related<super::favourite_gyms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FavouriteGyms.def()
    }
}

impl Related<super::favourite_trainings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FavouriteTrainings.def()
    }
}

impl Related<super::gyms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Gyms.def()
    }
}

impl Related<super::profile_pics::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProfilePics.def()
    }
}

impl Related<super::training_records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TrainingRecords.def()
    }
}

impl Related<super::training_templates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TrainingTemplates.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
