//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "exercise_templates")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub exercise_template_id: i32,
    pub active_duration: Time,
    pub active_force: i32,
    pub grip_type_id: i32,
    pub rest_duration: Time,
    pub rest_force: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::exercise_records::Entity")]
    ExerciseRecords,
    #[sea_orm(
        belongs_to = "super::grip_types::Entity",
        from = "Column::GripTypeId",
        to = "super::grip_types::Column::GripTypeId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    GripTypes,
    #[sea_orm(has_many = "super::training_exercises::Entity")]
    TrainingExercises,
}

impl Related<super::exercise_records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExerciseRecords.def()
    }
}

impl Related<super::grip_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GripTypes.def()
    }
}

impl Related<super::training_exercises::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TrainingExercises.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
