//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "exercise_records")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub exercise_record_id: i32,
    pub training_record_id: i32,
    pub exercise_template_id: i32,
    pub was_successful: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::exercise_templates::Entity",
        from = "Column::ExerciseTemplateId",
        to = "super::exercise_templates::Column::ExerciseTemplateId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ExerciseTemplates,
    #[sea_orm(has_many = "super::records::Entity")]
    Records,
    #[sea_orm(
        belongs_to = "super::training_records::Entity",
        from = "Column::TrainingRecordId",
        to = "super::training_records::Column::TrainingRecordId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TrainingRecords,
}

impl Related<super::exercise_templates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExerciseTemplates.def()
    }
}

impl Related<super::records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Records.def()
    }
}

impl Related<super::training_records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TrainingRecords.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
