//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "favourite_gyms")]
pub struct Model {
    pub climber_id: i32,
    pub gym_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::climbers::Entity",
        from = "Column::ClimberId",
        to = "super::climbers::Column::ClimberId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Climbers,
    #[sea_orm(
        belongs_to = "super::gyms::Entity",
        from = "Column::GymId",
        to = "super::gyms::Column::GymId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Gyms,
}

impl Related<super::climbers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Climbers.def()
    }
}

impl Related<super::gyms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Gyms.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
