//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "grip_types")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub grip_type_id: i32,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::exercise_templates::Entity")]
    ExerciseTemplates,
    #[sea_orm(has_many = "super::hangboard_grip_types::Entity")]
    HangboardGripTypes,
    #[sea_orm(has_many = "super::records::Entity")]
    Records,
}

impl Related<super::exercise_templates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExerciseTemplates.def()
    }
}

impl Related<super::hangboard_grip_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HangboardGripTypes.def()
    }
}

impl Related<super::records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Records.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
