//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "gyms")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub gym_id: i32,
    pub name: String,
    #[sea_orm(column_type = "Float")]
    pub location_x: f32,
    #[sea_orm(column_type = "Float")]
    pub location_y: f32,
    pub admin_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::climbers::Entity",
        from = "Column::AdminId",
        to = "super::climbers::Column::ClimberId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Climbers,
    #[sea_orm(has_many = "super::favourite_gyms::Entity")]
    FavouriteGyms,
    #[sea_orm(has_many = "super::hangboards::Entity")]
    Hangboards,
}

impl Related<super::climbers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Climbers.def()
    }
}

impl Related<super::favourite_gyms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FavouriteGyms.def()
    }
}

impl Related<super::hangboards::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Hangboards.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
