//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "hangboard_grip_types")]
pub struct Model {
    pub hangboard_id: i32,
    pub grip_type_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::grip_types::Entity",
        from = "Column::GripTypeId",
        to = "super::grip_types::Column::GripTypeId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    GripTypes,
    #[sea_orm(
        belongs_to = "super::hangboards::Entity",
        from = "Column::HangboardId",
        to = "super::hangboards::Column::HangboardId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Hangboards,
}

impl Related<super::grip_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GripTypes.def()
    }
}

impl Related<super::hangboards::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Hangboards.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
