//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "hangboards")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub hangboard_id: i32,
    pub owning_gym_id: i32,
    pub nickname: String,
    pub last_time_online: DateTime,
    pub last_time_calibrated: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::gyms::Entity",
        from = "Column::OwningGymId",
        to = "super::gyms::Column::GymId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Gyms,
    #[sea_orm(has_many = "super::hangboard_grip_types::Entity")]
    HangboardGripTypes,
}

impl Related<super::gyms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Gyms.def()
    }
}

impl Related<super::hangboard_grip_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HangboardGripTypes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
