//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude;

pub mod climbers;
pub mod climbing_grades;
pub mod exercise_records;
pub mod exercise_templates;
pub mod favourite_gyms;
pub mod favourite_trainings;
pub mod grip_types;
pub mod gyms;
pub mod hangboard_grip_types;
pub mod hangboards;
pub mod measurement_points;
pub mod profile_pics;
pub mod records;
pub mod training_exercises;
pub mod training_records;
pub mod training_templates;
