//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::climbers::Entity as Climbers;
pub use super::climbing_grades::Entity as ClimbingGrades;
pub use super::exercise_records::Entity as ExerciseRecords;
pub use super::exercise_templates::Entity as ExerciseTemplates;
pub use super::favourite_gyms::Entity as FavouriteGyms;
pub use super::favourite_trainings::Entity as FavouriteTrainings;
pub use super::grip_types::Entity as GripTypes;
pub use super::gyms::Entity as Gyms;
pub use super::hangboard_grip_types::Entity as HangboardGripTypes;
pub use super::hangboards::Entity as Hangboards;
pub use super::measurement_points::Entity as MeasurementPoints;
pub use super::profile_pics::Entity as ProfilePics;
pub use super::records::Entity as Records;
pub use super::training_exercises::Entity as TrainingExercises;
pub use super::training_records::Entity as TrainingRecords;
pub use super::training_templates::Entity as TrainingTemplates;
