//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "profile_pics")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub profile_pic_id: i32,
    pub url: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::climbers::Entity")]
    Climbers,
}

impl Related<super::climbers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Climbers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
