//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "records")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub record_id: i32,
    pub exercise_record_id: i32,
    pub used_grip_type_id: i32,
    pub duration: Time,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::exercise_records::Entity",
        from = "Column::ExerciseRecordId",
        to = "super::exercise_records::Column::ExerciseRecordId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ExerciseRecords,
    #[sea_orm(
        belongs_to = "super::grip_types::Entity",
        from = "Column::UsedGripTypeId",
        to = "super::grip_types::Column::GripTypeId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    GripTypes,
    #[sea_orm(has_many = "super::measurement_points::Entity")]
    MeasurementPoints,
}

impl Related<super::exercise_records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExerciseRecords.def()
    }
}

impl Related<super::grip_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GripTypes.def()
    }
}

impl Related<super::measurement_points::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MeasurementPoints.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
