//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "training_records")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub training_record_id: i32,
    pub climber_id: i32,
    pub training_template_id: i32,
    pub total_duration: Time,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::climbers::Entity",
        from = "Column::ClimberId",
        to = "super::climbers::Column::ClimberId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Climbers,
    #[sea_orm(has_many = "super::exercise_records::Entity")]
    ExerciseRecords,
    #[sea_orm(
        belongs_to = "super::training_templates::Entity",
        from = "Column::TrainingTemplateId",
        to = "super::training_templates::Column::TrainingTemplateId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TrainingTemplates,
}

impl Related<super::climbers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Climbers.def()
    }
}

impl Related<super::exercise_records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExerciseRecords.def()
    }
}

impl Related<super::training_templates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TrainingTemplates.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
