//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "training_exercises")]
pub struct Model {
    pub training_template_id: i32,
    pub exercise_template_id: i32,
    pub repetitions: i32,
    pub position: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::exercise_templates::Entity",
        from = "Column::ExerciseTemplateId",
        to = "super::exercise_templates::Column::ExerciseTemplateId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ExerciseTemplates,
    #[sea_orm(
        belongs_to = "super::training_templates::Entity",
        from = "Column::TrainingTemplateId",
        to = "super::training_templates::Column::TrainingTemplateId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TrainingTemplates,
}

impl Related<super::exercise_templates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExerciseTemplates.def()
    }
}

impl Related<super::training_templates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TrainingTemplates.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
