//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "training_templates")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub training_template_id: i32,
    pub name: String,
    pub creator_climber_id: i32,
    pub climbing_grade_id: i32,
    pub predicted_duration: Time,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::climbers::Entity",
        from = "Column::CreatorClimberId",
        to = "super::climbers::Column::ClimberId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Climbers,
    #[sea_orm(
        belongs_to = "super::climbing_grades::Entity",
        from = "Column::ClimbingGradeId",
        to = "super::climbing_grades::Column::ClimbingGradeId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ClimbingGrades,
    #[sea_orm(has_many = "super::favourite_trainings::Entity")]
    FavouriteTrainings,
    #[sea_orm(has_many = "super::training_exercises::Entity")]
    TrainingExercises,
    #[sea_orm(has_many = "super::training_records::Entity")]
    TrainingRecords,
}

impl Related<super::climbers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Climbers.def()
    }
}

impl Related<super::climbing_grades::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ClimbingGrades.def()
    }
}

impl Related<super::favourite_trainings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FavouriteTrainings.def()
    }
}

impl Related<super::training_exercises::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TrainingExercises.def()
    }
}

impl Related<super::training_records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TrainingRecords.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
